force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Log__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
			</value>
			<value>
                <fullName>PATCH</fullName>
			</value>
			<value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
			</value>
			<value>
                <fullName>Platform Event</fullName>
                <label>>Platform Event</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Module</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Successful__c.field-meta.xml
<CustomField>
    <fullName>Successful__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Successful</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/IntegrationLogSearchController.cls
public without sharing class IntegrationLogSearchController {
	@AuraEnabled
	public static List<Integration_Log__c> search(String text) {
		return search(new List<String> { text });
	}

	public static List<Integration_Log__c> search(List<String> searchTerms) {
		List<Integration_Log__c> filteredLogs = new List<Integration_Log__c>();

		if(searchTerms == null || searchTerms.isEmpty()) return filteredLogs;

		List<Integration_Log__c> logs = [select Id,CreatedDate,Name,Module__c,Successful__c,Request_Body__c,Endpoint__c,Method__c from Integration_Log__c where CreatedDate = TODAY order by CreatedDate desc limit 50000];
		for(Integration_Log__c log : logs) {
			Boolean include = false;
			for(String searchTerm : searchTerms) {
				if(log.Request_Body__c != null && log.Request_Body__c.containsIgnoreCase(searchTerm)) include = true;
				if(log.Endpoint__c != null && log.Endpoint__c.containsIgnoreCase(searchTerm)) include = true;
			}
			if(include) filteredLogs.add(log);
		}

		return filteredLogs;
	}

	public class LogsRelatedListProvider implements DynamicRelatedListUtil.DynamicRelatedListDataProvider {
		public DynamicRelatedListUtil.Info getRelatedListInfo(Id recordId, String fieldSetName) {
			if(recordId == null) return null;

			List<String> searchTerms = new List<String>();

			if(recordId.getSobjectType() == Account.getSObjectType()) {
				List<Account> accounts = [select Id,AccountNumber from Account where Id = :recordId];
				if(accounts.isEmpty()) return null;
				Account a = accounts[0];
				searchTerms.add(String.valueOf(a.Id));
				searchTerms.add(String.valueOf(a.AccountNumber));
			}

			List<Integration_Log__c> logs = search(searchTerms);

			Map<String, Schema.FieldSet> fieldSetMap = SObjectType.Integration_Log__c.fieldSets.getMap();
			Schema.FieldSet fs = fieldSetMap.get(fieldSetName);

			DynamicRelatedListUtil.Info relatedListInfo = new DynamicRelatedListUtil.Info(logs, fs);

			relatedListInfo.sortedBy = SObjectType.Integration_Log__c.fields.CreatedDate.name;
			relatedListInfo.sortedDirection = 'desc';

			return relatedListInfo;
		}
	}
}