force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Log__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
			</value>
			<value>
                <fullName>PATCH</fullName>
			</value>
			<value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
			</value>
			<value>
                <fullName>Platform Event</fullName>
                <label>>Platform Event</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Module</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/IntegrationLogSearchControllerTest.cls
@isTest
private class IntegrationLogSearchControllerTest {
	@TestSetup
	private static void setup() {
		Integration_Log__c l1 = new Integration_Log__c(Module__c = 'Test', Method__c = 'GET', Endpoint__c = 'http://systemx.com?recordId=123456', Request_Body__c = 'Some request from system X');
		Integration_Log__c l2 = new Integration_Log__c(Module__c = 'Test', Method__c = 'GET', Endpoint__c = 'http://systemy.com?recordId=123456', Request_Body__c = 'Some request from system Y');
		Integration_Log__c l3 = new Integration_Log__c(Module__c = 'Test', Method__c = 'GET', Endpoint__c = 'http://systemz.com?recordId=654321', Request_Body__c = 'Some request from system Z');
		insert new Integration_Log__c[] { l1, l2, l3 };
	}

	@IsTest
	private static void testSingleTerm() {

		Test.startTest();

		List<Integration_Log__c> logs = IntegrationLogSearchController.search('123456');

		Test.stopTest();

		System.assertEquals(2, logs.size());
	}

	@IsTest
	private static void testMultipleTerm() {

		Test.startTest();

		List<Integration_Log__c> logs = IntegrationLogSearchController.search(new List<String> { 'systemx', 'systemy'});

		Test.stopTest();

		System.assertEquals(2, logs.size());
	}

	@IsTest
	private static void testDynamicListForAccount() {
		Account a = new Account(Name = 'Test', AccountNumber = '123456');
		insert a;

		Test.startTest();

		IntegrationLogSearchController.LogsRelatedListProvider provider = new IntegrationLogSearchController.LogsRelatedListProvider();
		DynamicRelatedListUtil.Info info = provider.getRelatedListInfo(a.Id, SObjectType.Integration_Log__c.fieldSets.Latest_Logs.name);

		Test.stopTest();

		System.assertEquals(2, info.data.size());
	}
}