force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Log__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Module</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Origin_Data__c.field-meta.xml
<CustomField>
    <fullName>Origin_Data__c</fullName>
    <label>Origin Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Log_Event__e/Integration_Log_Event__e.object-meta.xml
<CustomObject>
    <label>Integration Log Event</label>
    <pluralLabel>Integration Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Log_Event__e/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Log_Event__e/fields/Origin_Data__c.field-meta.xml
<CustomField>
    <fullName>Origin_Data__c</fullName>
    <label>Origin Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/IntegrationLogUtilityTest.cls
@isTest
private class IntegrationLogUtilityTest {

    @testSetup
    private static void setup() {

    }

    @isTest
    private static void testOutbound() {
        HttpRequest request = new HttpRequest();
        request.setMethod('POST');
        request.setEndpoint('callou:Postman_Echo/post');
        request.setHeader('Content-Type','application/json');
        request.setBody('{"name": "Giovanni"}');
        HttpResponse response = new HttpResponse();

		Test.startTest();

        Integer randomNumberForModule = Integer.valueof((math.random() * 10));
        List<String> modules = new List<String> { 'Salesforce'};
        String requestModule = modules[Math.mod(randomNumberForModule,modules.size())];
        Integration_Log_Event__e log = IntegrationLogUtility.newLog(requestModule,String.valueOf(IntegrationLogUtility.Direction.Outbound));

        IntegrationLogUtility.includeHttpRequest(log, request);
        IntegrationLogUtility.includeHttpResponse(log, response);
        IntegrationLogUtility.publishLog(log);

        Test.stopTest();
    }

	@isTest
    private static void testInbound() {
        RestRequest request = new RestRequest();
		RestResponse response = new RestResponse();
		request.httpMethod = 'GET';
		request.requestUri = '/customers';
		RestContext.request = request;
		RestContext.response = response;

        Test.startTest();

        Integer randomNumberForModule = Integer.valueof((math.random() * 10));
        List<String> modules = new List<String> { 'Salesforce'};
        String requestModule = modules[Math.mod(randomNumberForModule,modules.size())];
        Integration_Log_Event__e log = IntegrationLogUtility.newLog(requestModule,String.valueOf(IntegrationLogUtility.Direction.Inbound));

		IntegrationLogUtility.includeRestContext(log);
		IntegrationLogUtility.publishLog(log);

        Test.stopTest();
    }

	@isTest
    private static void testExpierationQuery() {
		Test.startTest();

        String query = IntegrationLogUtility.buildIntegrationLogExpirationQuery();

        Test.stopTest();
	}

	@isTest
    private static void testRetry() {
		Integer randomNumberForModule = Integer.valueof((math.random() * 10));
        List<String> modules = new List<String> { 'Salesforce'};
        String requestModule = modules[Math.mod(randomNumberForModule,modules.size())];

		Integration_Log__c log = new Integration_Log__c(
			Module__c = requestModule,
			Origin_Data__c = JSON.serialize(new List<Integration_Log_Event__e> { new Integration_Log_Event__e(Module__c = requestModule) })
		);
		insert log;

		Test.startTest();

        IntegrationLogUtility.retryIntegration(new List<String> { log.Id });

        Test.stopTest();
	}

    @isTest
    private static void testOthers() {
        Test.startTest();

        Integer randomNumberForModule = Integer.valueof((math.random() * 10));
        List<String> modules = new List<String> { 'Salesforce'};
        String requestModule = modules[Math.mod(randomNumberForModule,modules.size())];
        Integration_Log_Event__e log = IntegrationLogUtility.newLog(requestModule,String.valueOf(IntegrationLogUtility.Direction.Outbound));

        IntegrationLogUtility.publishLog(log);
        IntegrationLogUtility.createLogAsync('','','','','','',200,'');
        IntegrationLogUtility.createLogSync('','','','','','',200,'');

        Test.stopTest();
    }
}