force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Log__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Module</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IntegrationLogCleanBatchTest.cls
@isTest
private class IntegrationLogCleanBatchTest {
	@testSetup
    private static void setup() {

        Integration_Log__c intlog = new Integration_Log__c(
            Module__c = 'Verifiable'
        );

        insert intlog;

    }

    @isTest
    private static void testLogCleanBatch() {

        Test.startTest();
        Id batchJobId = Database.executeBatch(new IntegrationLogCleanBatch(), 200);
        Test.stopTest();
        List<Integration_Log__c> logs = [SELECT Id FROM Integration_Log__c ];
        System.assert(logs.isEmpty());
    }
}